In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [6]:
my_array = np.array(mylist)

In [7]:
type(my_array)

numpy.ndarray

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
 np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(shape = (5,5))  # we can make our own arrays by giving the size

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape = (2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr 

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
# max value of an array

arr.max()

95

In [18]:
arr.argmax()

0

In [19]:
arr.min()

9

In [20]:
arr.argmin()

7

In [21]:
arr.mean()

60.8

In [22]:
# reshape arrays

In [23]:
arr.shape

(10,)

In [24]:
arr.reshape((2,5)) # we have certain formats in this

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [25]:
## indexing

In [27]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
row = 0